# Server config
server.port=7070

# Diagnostics
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

# H2 Database for local development
spring.datasource.url=jdbc:h2:mem:erp_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration (for JWT generation and validation)
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576d5A71347437
jwt.expiration=86400000 
